export const data = [
  {
    id: 1,
    text: 'همه چیز درمورد وکالت...',
    image: '',
    icon: 'micOutline2',
    type: 'mic',
  },
  {
    id: 2,
    text: '5 نکته وکالت',
    image: '',
    icon: 'micOutline2',
    type: 'mic',
  },
  {
    id: 3,
    text: 'همه چیز درمورد وکالت',
    image: '',
    icon: 'micOutline2',
    type: 'mic',
  },
  {
    id: 4,
    text: '5 نکته وکالت',
    image: '',
    icon: 'playVideo',
    type: 'video',
  },
  {
    id: 5,
    text: 'همه چیز درمورد وکالت',
    image: '',
    icon: 'playVideo',
    type: 'video',
  },
  {
    id: 6,
    text: 'همه چیز درمورد وکالت',
    image: '',
    icon: 'micOutline2',
    type: 'mic',
  },
  {
    id: 7,
    text: 'همه چیز درمورد وکالت...',
    image: '',
    icon: 'micOutline2',
    type: 'mic',
  },
  {
    id: 8,
    text: '',
    image: '',
    icon: '',
    type: 'plain',
  },
  {
    id: 9,
    text: '',
    image: '',
    icon: '',
    type: 'plain',
  },
];
